# pandas - Python data analysis library

**Author: Trevor Faske, Chandra Sarkar  
Modified: 02/15/2022**

pandas is a must learn tool for data science. It is a powerful python package and swiss army knife for all data analysis. "The name is derived from the term 'panel data', an econometrics term for data sets that include observations over multiple time periods for the same individuals. Also a play on the phrase 'Python data analysis.'" - wikipedia

pandas works with the data structure called **DataFrame** (same as in R). This consists of a matrix with rows and columns and will very similar to an excel spreadsheet or csv file. pandas allows you to easily manipulate, filter, summarize, and merge data for downstream processing. pandas is part of the SciPy (https://www.scipy.org/) ecosystem so works great for plotting and data analysis. 

## Resources

- https://github.com/jvns/pandas-cookbook
- https://www.w3schools.com/python/ (great NumPy intro)
- https://pandas.pydata.org/docs/getting_started/tutorials.html (community tutorials)
- https://pandas.pydata.org/docs/user_guide/index.html

## Installing libraries

Python is extremely efficient and only has a few commands loaded and installed from the beginning. There are libraries we will have to install and import as needed to use. 

Everyone should have pip3 or conda available and these commands will be used to install needed libraries from the terminal. 

**If using pip3**:  

`$ pip3 install numpy`   
`$ pip3 install pandas`
    
You might get a permissions error. If so, install like:  
`$ pip3 install --user pandas`

**If using conda**:  

`$ conda install -c anaconda numpy`  
`$ conda install -c anaconda pandas`


## Importing libraries

Python only has a few base commands and is extremely effecient. Libraries must be imported before use to make the commands available. There is a few ways to import libraries by creating aliases or only accessing paticular functions within libraries. 

Basic import: 

`import numpy`  
`import pandas`  


Examples of more common ways of importing:  

`import numpy,pandas` #import multiple libraries in single line  
`import numpy as np` #import package as alias  
`from pandas import DataFrame` #import only specific function from library

Common aliases you will see when searching issues:  

`import numpy as np`  
`import pandas as pd`

## Getting started with NumPy

#### Resource: https://www.w3schools.com/python/numpy_intro.asp

NumPy is a popular array – processing package of Python that also does a lot of mathmatical processes. Everything is array/matrix based and works faster than a list. pandas uses many of this same syntax so might be useful to know a few commands!

### ndarrays

import numpy

In [2]:
import numpy as np 

#### create 1-D array

In [3]:
d1 = np.array([1,3,5,2,4,6])
print(d1)
type(d1)

[1 3 5 2 4 6]


numpy.ndarray

#### create 2-D array

In [4]:
d2 = np.array([[1,3,5],[2,4,6]])
print(d2)

[[1 3 5]
 [2 4 6]]


#### get dimensions and total size

In [5]:
print(d2.shape) #rows, columns
print(d2.size) 

(2, 3)
6


### Accessing and indexing arrays work very similar to lists but with added dimension. Very similar to R indexing 

array[row,column] #REMEMBER starts at 0

In [6]:
# 2nd row, 1st column 
print(d2[1,0]) 

# 1st row, 3rd column
print(d2[0,2])

2
5


#### Slicing works very similarly to lists

In [7]:
#extract first 2 elements of the 2nd row
print(d2[1,:2])

[2 4]


### arange and reshape array format

In [8]:
d1 = np.array([1,3,5,2,4,6])
print(d1)
d1.reshape(2,3)

[1 3 5 2 4 6]


array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
d2.reshape(1,6)  

array([[1, 3, 5, 2, 4, 6]])

#### create 1D array 0-9

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### array 0 to 50 by 5 (start,stop,step)

In [11]:
np.arange(0,51,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Random number generator

very useful for permutation techniques or simulating data

import random from numpy

In [12]:
from numpy import random

#### Generate a random float from 0 to 1

In [13]:
random.rand()

0.27571784506413344

#### generate 5 random float from 0 to 1

In [14]:
random.rand(5)

array([0.57438932, 0.72654951, 0.27828207, 0.13242748, 0.74150186])

#### generate random integer between 0-99

In [15]:
random.randint(100)

45

#### generate 7 random integer between 0-99

In [16]:
random.randint(100, size = 7)

array([50, 98, 24, 35, 32, 16, 55])

#### generate 2D array random integer between 0-99

In [18]:
random.randint(100, size=(2,3))

array([[77, 17, 49],
       [89, 29,  6]])

### Choose or randomly sample list/array

#### sample from list

In [17]:
random.choice([3, 5, 7, 9])

7

#### sample 4 elements from list 

In [19]:
random.choice([3, 5, 7, 9],size=(3,4))

array([[9, 9, 9, 7],
       [9, 9, 5, 5],
       [9, 9, 5, 3]])

### Math (https://numpy.org/doc/stable/reference/routines.math.html)

#### generate 100 random numbers from 1 to 1000 and get length, max, min, mean

In [21]:
x = random.randint(1000,size=100)

print(len(x))
print(x.max())
print(x.min())
print(x.mean())
print(x)

100
987
4
495.14
[978 437 344 391 470 987 552  83 310 714 965 413 381 981 317  34 581 201
 194 339 800  41 119 793 983 845 267 896 626 256  73 354 781  82 951 215
 861 114 701 190   6 169 132 759 374 483 812   7 326 621 481 671  18 785
 334 945 839 978 570 399 169 658 957 606 319 864 418 624 732 325 837 312
 154   4 786 501 752  24 790 206 152 537 261 334 796  40 961 347 250 819
 313 777 489 752 667 516 488 210 620 818]


## Getting started with pandas - finally to the good stuff! 

#### side note: 

Nice thing about jupyter notebooks is it accepts linux commands, just as the terminal

In [1]:
pwd

'/Users/ariellejewelpastore/Desktop/hw4/Part.3.PythonProgramming/Pandas'

In [2]:
### Change to pandas working directory
pandas_dir = '/Users/ariellejewelpastore/Desktop/hw4/Part.3.PythonProgramming/Pandas'

In [3]:
cd $pandas_dir

/Users/ariellejewelpastore/Desktop/hw4/Part.3.PythonProgramming/Pandas


In [4]:
!mkdir new_dir

In [5]:
!rmdir new_dir

### Read and write files (using DataFrame) 

Make sure you have **states_covid.csv** in your pandas directory from above.  

Data downloaded from: https://github.com/COVID19Tracking/covid-tracking-data (data stopped updating March, 2021)  

**PATH**: You need your path to be correct to load files. Go to directory for day 5 in your terminal and type `pwd`. Copy this path in front of **states_covid.csv**

In [6]:
import pandas as pd

state_covid_df = pd.read_csv('states_covid.csv') #read in csv
state_covid_df.head() #views the top 5 lines

date state    death  deathConfirmed  deathIncrease  deathProbable  \
0  2021-02-23    AK    290.0             NaN              0            NaN   
1  2021-02-23    AL   9660.0          7575.0             68         2085.0   
2  2021-02-23    AR   5377.0          4321.0             14         1056.0   
3  2021-02-23    AS      0.0             NaN              0            NaN   
4  2021-02-23    AZ  15650.0         13821.0            148         1829.0   

   hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
0        1260.0                  1260.0                   38.0   
1       45250.0                 45250.0                  762.0   
2       14617.0                 14617.0                  545.0   
3           NaN                     NaN                    NaN   
4       57072.0                 57072.0                 1515.0   

   hospitalizedIncrease  ...  totalTestResults  totalTestResultsIncrease  \
0                     9  ...         1653425.0                      4640   
1                   122  ...         2265086.0                      4825   
2                    47  ...         2609837.0                      4779   
3                     0  ...            2140.0                         0   
4                    78  ...         7478323.0                     19439   

   totalTestsAntibody  totalTestsAntigen  totalTestsPeopleAntibody  \
0                 NaN                NaN                       NaN   
1                 NaN                NaN                  115256.0   
2                 NaN                NaN                       NaN   
3                 NaN                NaN                       NaN   
4            435091.0                NaN                       NaN   

   totalTestsPeopleAntigen  totalTestsPeopleViral  \
0                      NaN                    NaN   
1                      NaN              2265086.0   
2                 436309.0                    NaN   
3                      NaN                    NaN   
4                      NaN              3709365.0   

   totalTestsPeopleViralIncrease  totalTestsViral  totalTestsViralIncrease  
0                              0        1653425.0                     4640  
1                           4825              NaN                        0  
2                              0        2609837.0                     4779  
3                              0           2140.0                        0  
4                           6212        7478323.0                    19439  

[5 rows x 41 columns]

In [7]:
state_covid_df.shape #row, column length

(20108, 41)

In [8]:
state_covid_df.columns #views the column names

Index(['date', 'state', 'death', 'deathConfirmed', 'deathIncrease',
       'deathProbable', 'hospitalized', 'hospitalizedCumulative',
       'hospitalizedCurrently', 'hospitalizedIncrease', 'inIcuCumulative',
       'inIcuCurrently', 'negative', 'negativeIncrease',
       'negativeTestsAntibody', 'negativeTestsPeopleAntibody',
       'negativeTestsViral', 'onVentilatorCumulative', 'onVentilatorCurrently',
       'positive', 'positiveCasesViral', 'positiveIncrease', 'positiveScore',
       'positiveTestsAntibody', 'positiveTestsAntigen',
       'positiveTestsPeopleAntibody', 'positiveTestsPeopleAntigen',
       'positiveTestsViral', 'recovered', 'totalTestEncountersViral',
       'totalTestEncountersViralIncrease', 'totalTestResults',
       'totalTestResultsIncrease', 'totalTestsAntibody', 'totalTestsAntigen',
       'totalTestsPeopleAntibody', 'totalTestsPeopleAntigen',
       'totalTestsPeopleViral', 'totalTestsPeopleViralIncrease',
       'totalTestsViral', 'totalTestsViralIncrease'

While the above example is very straight forward with a clean csv file, **pd.read_csv()** is a very powerful tool for reading/parsing complicated data. For more information of all the commands it has, visit here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html. Otherwise, google is your best friend. Any issue you have, someone has figured it out already. 



One common issue with all data formats are Dates. Pandas has a way to read dates in without much headache and nice features for doing things with dates. You can also only select various columns, rename headers, remove headers, change what characters you want to be recognized as NAs, etc.

Below is an example of some of the things you can do.

In [9]:
state_covid_sub_df = pd.read_csv('states_covid.csv',usecols=['date','state','death','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True)
state_covid_sub_df.head()

date state    death   negative  positive  totalTestResults
0 2021-02-23    AK    290.0        NaN   55560.0         1653425.0
1 2021-02-23    AL   9660.0  1882180.0  488973.0         2265086.0
2 2021-02-23    AR   5377.0  2359571.0  316593.0         2609837.0
3 2021-02-23    AS      0.0     2140.0       0.0            2140.0
4 2021-02-23    AZ  15650.0  2953210.0  810658.0         7478323.0

#### check and make sure dtypes are right (dates specifically)

In [11]:
state_covid_sub_df.dtypes

date                datetime64[ns]
state                       object
death                      float64
negative                   float64
positive                   float64
totalTestResults           float64
dtype: object

### Problems with Null Values

Null values can interfere with data interpretation and analysis. With pandas, detecting and editing null values is easy.

Let’s identify all locations in the survey data that have null (missing or NaN) data values. We can use the isnull method to do this. The isnull method will compare each cell with a null value. If an element has a null value, it will be assigned a value of True in the output object.

In [12]:
pd.isnull(state_covid_sub_df)

date  state  death  negative  positive  totalTestResults
0      False  False  False      True     False             False
1      False  False  False     False     False             False
2      False  False  False     False     False             False
3      False  False  False     False     False             False
4      False  False  False     False     False             False
...      ...    ...    ...       ...       ...               ...
20103  False  False   True      True     False              True
20104  False  False   True      True     False              True
20105  False  False   True      True     False              True
20106  False  False   True      True     False              True
20107  False  False   True      True      True              True

[20108 rows x 6 columns]

In [15]:
# To select just the rows with NaN values, we can use the 'any()' method
state_covid_sub_df[pd.isnull(state_covid_sub_df).any(axis=1)]

date state    death  negative   positive  totalTestResults
0     2021-02-23    AK    290.0       NaN    55560.0         1653425.0
5     2021-02-23    CA  49563.0       NaN  3450058.0        47513367.0
7     2021-02-23    CT   7572.0       NaN   276691.0         6198707.0
8     2021-02-23    DC    998.0       NaN    39844.0         1201605.0
11    2021-02-23    GA  16927.0       NaN   990821.0         7076399.0
...          ...   ...      ...       ...        ...               ...
20103 2020-01-17    WA      NaN       NaN        0.0               NaN
20104 2020-01-16    WA      NaN       NaN        0.0               NaN
20105 2020-01-15    WA      NaN       NaN        0.0               NaN
20106 2020-01-14    WA      NaN       NaN        0.0               NaN
20107 2020-01-13    WA      NaN       NaN        NaN               NaN

[4970 rows x 6 columns]

In [14]:
# What will this do?
temp_var = state_covid_sub_df[pd.isnull(state_covid_sub_df['death'])]['death']
print(temp_var)

17083   NaN
17139   NaN
17195   NaN
17251   NaN
17307   NaN
         ..
20103   NaN
20104   NaN
20105   NaN
20106   NaN
20107   NaN
Name: death, Length: 878, dtype: float64


#### Dealing with null values

We can replace all NaN values with zeroes using the .fillna() method (after making a copy of the data so we don’t lose our work)

In [16]:
#The name - "no_null_state_covid_sub_df" is probably more explanatory. But we will use a shorter name.
nnl_covid_df = state_covid_sub_df.copy()
nnl_covid_df['death'] = state_covid_sub_df['death'].fillna(0)

In [17]:
# test mean of the column with null values not filled in
state_covid_sub_df['death'].mean()

3500.500624024961

In [18]:
# test mean of the column with null values filled in as 0
nnl_covid_df['death'].mean()

3347.6540183011734

### write DataFrame to outfile 
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)

**note:** make sure you provide the path or are in the working directory you want

In [ ]:
outfile_path = pandas_dir + 'state_covid_sub.csv'
#outfile_path = os.path.join(pandas_dir,'state_covid_sub.csv')
state_covid_sub_df.to_csv(path_or_buf=outfile_path,index=False)

## Manipulate DataFrame 

While read_csv is a powerful tool, we are going to subset, rename, change dtypes, and filter on our own just as a practice

In [ ]:
state_covid_df = pd.read_csv('states_covid.csv')

#### Select only columns date, state, death, negative, postive, totalTestResults 

In [ ]:
new_covid_df = state_covid_df[['date','state','death','positive','negative','totalTestResults']]
new_covid_df.head() 

#### two ways to change column names totalTestResults to total 
first changes all colums:  
`new_covid_df.columns = ['date','state','death','positive','negative','total']`  

Second code below:  
changes only selected column  
axis = (0 = rows, 1 = columns)  
inplace=True replaces the current DataFrame, same as (df = df.DOSOMETHING) 

In [ ]:
new_covid_df.rename({'totalTestResults':'total'},axis=1,inplace=True)

In [ ]:
new_covid_df.head()

#### two ways to reorder columns
`new_covid_df = new_covid_df[['date','state','total','negative','positive','death']]`  
`new_covid_df = new_covid_df.iloc[:,[0,1,5,4,3,2]]` #iloc is how you access df like a matrix

In [ ]:
new_covid_df.iloc[2,3]

In [ ]:
new_covid_df = new_covid_df[['date','state','total','negative','positive','death']]

#### add a column (positivity rate)
`new_covid_df['rate'] = new_covid_df.positive / new_covid_df.total` #alternate way

In [ ]:
new_covid_df['rate'] = new_covid_df['positive'] / new_covid_df['total']

#### Date manipulation
There's lots of crazy stuff you can do with dates, not going into it too much but just letting you know you can do it and something worth looking into

In [ ]:
new_covid_df["date"]= pd.to_datetime(new_covid_df["date"],yearfirst=True) 
new_covid_df.info()

#### add a column for day of year/julian date

In [ ]:
new_covid_df['dayofyear'] = new_covid_df['date'].dt.dayofyear
new_covid_df.head()

#### subsetting/filtering data
subset or filter on multiple columns and data types (numeric or string)

First, we'll subset on Nevada only and peak in to what it is doing

In [ ]:
new_covid_df.state == 'NV'

You can't really see where but it is outputtig a list of boolean (True,False) in the order they are found. If you put this statement as an index, it will keep only the Trues

**subsetting NV only**

In [ ]:
NV_covid_df = new_covid_df[new_covid_df.state == 'NV']
NV_covid_df.head()

Let's do one more filtering on states and something else numeric

| means or   
& means and

In [ ]:
new_covid_df[(new_covid_df.state == 'NV') & (new_covid_df.rate > 0.10)]

df.query() is another way that might look a little cleaner for more complicated filtering  
be careful with syntax of quotations 

In [ ]:
new_covid_df.query("state == 'NV' & rate > 0.10")

### Sort dataframe 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

**sort and select top 5 positive days**

In [ ]:
#new_covid_df = new_covid_df.sort_values('positive',ascending=False,inplace=False)
new_covid_df.sort_values('positive',ascending=False,inplace=True)
new_covid_df.head()

## Creating a DataFrame

There are a few different ways to create a DataFrame from scratch or non-csv/excel formatted data

### DataFrame from NumPy  
ndarray formats translate nicely into DataFrames. Let's generate some fake data using the random function in NumPy to demonstrate. Say this made up data is different sites and persons ratings (0-5) of 8 GREAT Nicholas Cage movies. 

In [ ]:
###generate a random array (8 rows, 6 columns) with values ranging 0-4  
movieRank_np = random.randint(5, size=(8,6))

Lets make up some column names for this data  

In [ ]:
col_names = ['RottenTomatoes','IMBD','MovieCritic','Julie','Trevor','Jahner']
movieRank_df = pd.DataFrame(movieRank_np,columns=col_names)

Lets add a column for movie titles and make them the index as well

In [ ]:
movies = ['FaceOff','RaisingArizona','WeatherMan','WickerMan','Adaptation','Gone60Seconds','ConAir','TheRock']  
movieRank_df['movie'] = movies  
movieRank_df.index = movies
movieRank_df

In [ ]:
movieRank_df.mean(axis=0) #mean rank per movie, axis = [row = 0 ,column = 1]

We all know these numbers are of course wrong because there's no rank below a 5 that should be given, but just an example

## Summarizing DataFrame

https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

You will need **Bloom_etal_2018_Reduced_Dataset.csv** from Homework 3 python  

Summarizing data is important for figures, statistics, and general reporting

make sure you're in the right directory and have the correct csv

In [ ]:
# cd $pandas_dir

In [ ]:
bloom_df = pd.read_csv('Bloom_etal_2018_Reduced_Dataset.csv')
print(bloom_df.shape)
print(bloom_df.head())

Let's check out how many options there are for the *Reg* column

In [ ]:
bloom_df['Reg'].unique()

Now lets get some summary stats for *logbodysize* and *tropic_position* based on being diadromous or non-diadromous

In [ ]:
bloom_reg_df = bloom_df.groupby('Reg',as_index=True).agg(['mean','count'])
bloom_reg_df

In [ ]:
bloom_reg_df.index

**WARNING:** as you can see, this produced the desired result but the column names are now stacked and have what is known as a *MultiIndex* column name and needs to be flattened. You only need to worry about this if summarizing over more than one column

In [ ]:
bloom_reg_df.columns

Let's join the MultiIndex to a single column index like we are used to.

In [ ]:
bloom_reg_df.columns = bloom_reg_df.columns.map('_'.join)
bloom_reg_df

In [ ]:
x = bloom_reg_df['logbodysize_count']
print(x)
print(x)

## lastly, couple other useful (maybe) things

### matplotlib

Not going to go too much into this but just so you know it exists. matplotlib is the most common plotting function in python I think. There are many others though! matplotlib is nice cause it's in the SciPy family so works nicely with pandas and NumPy and other things. Also allows you to integrate ggplot and seaborn if you would like. 

Simple figures with Covid data. Read in the data again, run through same code to get only NV data

In [ ]:
state_covid_sub_df = pd.read_csv('states_covid.csv',usecols=['date','state','death','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True,index_col=None)
state_covid_sub_df.head()

Make sure you index as date. Plot will automatically recogize it for axis. 

In [ ]:
NV_covid_df = state_covid_sub_df[state_covid_sub_df.state == 'NV']
NV_covid_df.index = NV_covid_df['date']
NV_covid_df.head()

Load matplotlib.pyplot, plot death over time

In [ ]:
import matplotlib.pyplot as plt

# Make the graphs a bit prettier, and bigger
plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.figsize'] = (15, 5)

#### plot deaths over time ####
NV_covid_df.death.plot()

Remember that python has great built in date attributes. Plot deaths by day and find the days with the most deaths 

In [ ]:
#### deaths by day of the week ####
weekday_counts = NV_covid_df.groupby(NV_covid_df['date'].dt.day_name()).aggregate(sum)
weekday_counts

weekday_counts.death.plot(kind='bar')

weekday_counts[weekday_counts.death == weekday_counts.death.max()]

Days with most deaths are **Tuesday**. Anyone know why? "most places are closed on the weekend, many counts are reports happen on monday" 

### Other useful libraries

- BioPython / SeqIO (molecular biology)
- scikit-learn (statistics and machine learning)
- TenserFlow (Deep Learning)
- BeautifulSoup (Scraping HTML)
- seaborn (extension of matplotlib)
- plotly (more ploting)
- iPython (notebooks / will go over in Julie's course)
- r2py (run R script within python)
- literally anything you can think of, a library exists for it


# ta-daaaa, you're a data science wizard now